---
- name: Add deploy Keys to hosts Playbook
  vars_files:
    - inventory/group_vars/development
  hosts: "{{ host_or_group }}"
  gather_facts: false
  become: true
  tasks:
  - name: Install devops Key Task
    ansible.posix.authorized_key:
      user: devops
      state: present
      key: "{{ item }}"
    with_file:
      - ~/vg/projects/public_keys/devops_id_rsa.pub
      - ~/.ssh/id_rsa.pub