---
- name: Create DevOps User Playbook
  vars_files:
    - inventory/group_vars/development
  hosts: "{{ host_or_group }}"
  gather_facts: false
  become: true
  tasks:
    - name: Create DevOps User Task
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
        password: "{{ default_user_password | password_hash('sha512', 'A512') }}"
        shell: /bin/bash
        groups: "{{ admin_group }}"
        create_home: true
        comment: 'Ansible DevOps Account'
        expires: -1
      loop: "{{ devops_users }}"

    - name: Install SSH Key Task
      ansible.posix.authorized_key:        
        user: devops
        state: present
        manage_dir: true
        key: "{{ item }}"
      with_file:
        - ~/vg/projects/public_keys/devops_id_rsa.pub
        - ~/.ssh/id_rsa.pub

    - name: Setup DevOps Sudo Access
      ansible.builtin.copy:
        dest: /etc/sudoers.d/devops
        content: 'devops ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s