---
- name: Create Admin Users Playbook
  vars_files:
    - inventory/group_vars/all
    - inventory/group_vars/development
  hosts: "{{ host_or_group }}"
  gather_facts: false
  become: true
  tasks:
    - name: Create Admin Users Task
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
        password: "{{ default_user_password | password_hash('sha512', 'A512') }}"
        shell: /bin/bash
        groups: "{{ admin_group }}"
        create_home: true
        comment: 'User "{{ item }}" Admin Account'
        expires: -1
      loop: "{{ users }}"