---
- name: Deploy Java 11 Playbook
  vars_files:    
    - inventory/group_vars/infra
  vars:
    java: java-11-openjdk    
  hosts: "{{ host_or_group }}"
  gather_facts: true
  become: true
  tasks:
    - name: Fetch java version Task
      ansible.builtin.shell: java -version
      changed_when: False
      register: java_result
      failed_when: False
  
    - name: Install {{ java }} Package Task
      ansible.builtin.dnf:
        name:
          - "{{ java }}"
        update_cache: yes
        state: latest
      when: java_result.rc!=0

    - name: Print java facts Task
      ansible.builtin.debug:
        var: java_result